// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPCqzoA5nLmler2u_6s4VDDd-9m_0m0iU',
    appId: '1:791583603828:web:78ebb9ee19c2c5ca5e6521',
    messagingSenderId: '791583603828',
    projectId: 'sams-d2236',
    authDomain: 'sams-d2236.firebaseapp.com',
    storageBucket: 'sams-d2236.firebasestorage.app',
    measurementId: 'G-MWJ4YZ7XHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxiyNRh6gaMbF3nfKnsN_e9W5Vt4AoXHc',
    appId: '1:791583603828:android:00e8940779bc0fd35e6521',
    messagingSenderId: '791583603828',
    projectId: 'sams-d2236',
    storageBucket: 'sams-d2236.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiT03-9FTl9BZhfMGwM1_F6SaWU37slgk',
    appId: '1:791583603828:ios:ca3d7fb6577d26405e6521',
    messagingSenderId: '791583603828',
    projectId: 'sams-d2236',
    storageBucket: 'sams-d2236.firebasestorage.app',
    iosClientId: '791583603828-26keabsa1jb2kbtnp050l1l3och4qrbn.apps.googleusercontent.com',
    iosBundleId: 'com.example.samsFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiT03-9FTl9BZhfMGwM1_F6SaWU37slgk',
    appId: '1:791583603828:ios:ca3d7fb6577d26405e6521',
    messagingSenderId: '791583603828',
    projectId: 'sams-d2236',
    storageBucket: 'sams-d2236.firebasestorage.app',
    iosClientId: '791583603828-26keabsa1jb2kbtnp050l1l3och4qrbn.apps.googleusercontent.com',
    iosBundleId: 'com.example.samsFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPCqzoA5nLmler2u_6s4VDDd-9m_0m0iU',
    appId: '1:791583603828:web:c86509dbfe2178a05e6521',
    messagingSenderId: '791583603828',
    projectId: 'sams-d2236',
    authDomain: 'sams-d2236.firebaseapp.com',
    storageBucket: 'sams-d2236.firebasestorage.app',
    measurementId: 'G-DNM11B7BD3',
  );

}