// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARJKtpBVCAz9MSaj0qhChhGmYrzDQwm2g',
    appId: '1:180319974548:web:61f1467f6c9c6b2fe43081',
    messagingSenderId: '180319974548',
    projectId: 'sams-ae15c',
    authDomain: 'sams-ae15c.firebaseapp.com',
    storageBucket: 'sams-ae15c.firebasestorage.app',
    measurementId: 'G-PD54HPH036',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJLUFdeB1sfovYJdKElMoPw4ADB-LVMxY',
    appId: '1:180319974548:android:252115a6bf9f9c30e43081',
    messagingSenderId: '180319974548',
    projectId: 'sams-ae15c',
    storageBucket: 'sams-ae15c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqONAOPRz8uOw2uWcNQdhPZVl2idsM0Kg',
    appId: '1:180319974548:ios:a8b3dee5f1534f10e43081',
    messagingSenderId: '180319974548',
    projectId: 'sams-ae15c',
    storageBucket: 'sams-ae15c.firebasestorage.app',
    iosBundleId: 'com.example.samsFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqONAOPRz8uOw2uWcNQdhPZVl2idsM0Kg',
    appId: '1:180319974548:ios:a8b3dee5f1534f10e43081',
    messagingSenderId: '180319974548',
    projectId: 'sams-ae15c',
    storageBucket: 'sams-ae15c.firebasestorage.app',
    iosBundleId: 'com.example.samsFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARJKtpBVCAz9MSaj0qhChhGmYrzDQwm2g',
    appId: '1:180319974548:web:17f0d2d5934336b4e43081',
    messagingSenderId: '180319974548',
    projectId: 'sams-ae15c',
    authDomain: 'sams-ae15c.firebaseapp.com',
    storageBucket: 'sams-ae15c.firebasestorage.app',
    measurementId: 'G-2K89F6YXCB',
  );

}